### ISSUE TITLE
error executing yo react-require ::  missing .gitignore

### ISSUE THREAD

**Issue by enjine** [jakowicz/generator-react-require#1]
$ yo react-require
fs.js:568
  function strWrapper(err, written) {
                ^
Error: ENOENT, no such file or directory '/Users/zeuben/.npm-packages/lib/node_modules/generator-react-require/app/templates/.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at module.exports (/Users/zeuben/.npm-packages/lib/node_modules/generator-react-require/node_modules/yeoman-generator/node_modules/isbinaryfile/index.js:14:25)
    at _prepCopy (/Users/zeuben/.npm-packages/lib/node_modules/generator-react-require/node_modules/yeoman-generator/lib/actions/actions.js:46:16)
    at copy (/Users/zeuben/.npm-packages/lib/node_modules/generator-react-require/node_modules/yeoman-generator/lib/actions/actions.js:79:19)
    at module.exports.yeoman.generators.Base.extend.copyFiles (/Users/zeuben/.npm-packages/lib/node_modules/generator-react-require/app/index.js:23:14)
    at /Users/zeuben/.npm-packages/lib/node_modules/generator-react-require/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback](timers.js:358:17)

**Comment by jakowicz** [comment]
I apologise for the slow reply. I actually fixed this about a month ago. I think there was a change regarding how Yeoman handles .gitignore files. 

If you run

```
npm update -g generator-react-require
```

Then

```
yo react-require
```

The problem will be resolved.
